Makefile, etc/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml, etc/delphix-platform/ansible/apply, etc/delphix-platform/upgrade/unpack-image
This change adds a script to this repository that can be used to unpack
an upgrade image, such that the upgrade-scripts contained in that image
can then be used to upgrade the appliance.
=> Add script + ansible logic to unpack upgrade image

etc/delphix-platform/upgrade/unpack-image
Currently, when using the "-f" option with the "unpack-image" script,
it'll fail and simulateously clear the contents "/var/dlpx-update". This
change fixes how the $UPDATE_DIR and $VERSION variables are expanded
when executing the "rm -rf" command, resolving the issue.
=> Fix "unpack-image" when "-f" option is used

etc/delphix-platform/ansible/apply
This change passes in the name of the root filesystem to ansible
playbooks to enable them to make modifications to root filesystem
properties without implementing root filesystem discovery logic within
ansible.
I tested this by applying this diff to an already installed apply script, and
modifying the virtualization package's ansible role to set a zfs property
on the filesystem.
=> Pass in the name of the root filesystem to ansible playbooks

etc/delphix-platform/upgrade/unpack-image
* Adds progress report to `unpack-image` script to allow app-gate to consume progress.
Manually tested
```
delphix@harry-dlpxtrunk:~$ sudo /etc/delphix-platform/upgrade/unpack-image internal-dev.upgrade.tar.gz
Progress increment: 00:22:43:072390972+0000, 10, Extracting upgrade image.
Progress increment: 00:24:33:202712234+0000, 80, Verifying format.
Progress increment: 00:24:33:239222093+0000, 100, Unpacking successful.
delphix@harry-dlpxtrunk:~$ cd /var/dlpx-update/2018.11.13.9/
delphix@harry-dlpxtrunk:/var/dlpx-update/2018.11.13.9$ ls
common.sh  db  execute  pool  public  upgrade  upgrade-container  verify  verify-impl  version.info
delphix@harry-dlpxtrunk:/var/dlpx-update/2018.11.13.9$
```
=> LX-1598 Add progress report in unpack-image script

etc/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
Tested by scp-ing updated main.yml onto target vm and rebooting.
=> Remove the ubuntu welcome banner, help info, and last login when ssh-ing

etc/delphix-platform/ansible/apply, lib/systemd/system/delphix-platform.service
Problem
=======
Using "systemd-analyze" to inspect the bootup latency, we can quickly
see the "delphix-platform" adds considerable latency to bootup time.
Since the "delphix-mgmt" service depends on "delphix-platform", any time
required to execute the "delphix-platform" service directly affects the
latency for the "delphix-mgmt" to come up after a reboot.
Here's an example from a system without this change:
$ systemd-analyze blame | head -n2
1min 20.155s delphix-mgmt.service
18.660s delphix-platform.service
From this, we see it takes over 18s to execute the "delphix-platform"
service; this translates to 18 seconds of additional downtime for the
"delphix-mgmt" service.
Solution
========
To address this issue, this change modifies the "delphix-platform"
service to only run the ansible …
=> Apply configuration once, to reduce bootup latency

etc/systemd/journald.conf.d/override.conf
The current log size limit (250M) is met quite quickly in the context of our normal blackbox testing (I was looking at the precheckin scope, in particular). I was able to determine that at the worst point, the journal only has 20 minutes worth of logs. Since this test scope runs about 3 hours, I decided to increase the size limit by a factor of 10 so that logs are available that cover the whole duration (plus some buffer, as tests might not be looked at immediately).
=> DLPX-61685 Increase journalctl log storage space

debian/rules, var/target/pr/README
**DESCRIPTION**
Directory /var/target/pr must be present on the system for
SCSI-3 persistent reservations to work as the LIO "target" driver
creates files under it to store persistent reservation
information.
This is related to https://jira.delphix.com/browse/DLPX-61906.
**TESTING**
- pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/341/
- Tested that SCSI-3 reservations work by running tests on a Windows target environment against a LUN exposed by the DE:
```
C:\Users\dtully\Downloads>scsicmd -d3 -sscsi3_test
...
====>  SCSI-3 PERSISTENT OPERATION TESTS: All tests are PASSED on harddisk3.
```
- Jeff tested that we can successfully add the LUN to a Windows Server Failover Cluster.
=> Enable SCSI-3 persistent reservations

etc/cron.daily/delphix-upgrade-logs, var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
When performing an upgrade via the virtualization API, the application
will attempt to create a file in "/var/log/delphix-upgrade" prior to
executing any of the upgrade scripts. This file creation currently fails
because the "/var/log/delphix-upgrade" directory will not exist at that
point (that directory is created by the upgrade scripts).
This change fixes the problem by creating this directory via the
delphix-platform service (which runs on first boot, prior to the
virtualization application running), and also updates the associated
cron entry to ensure the directory is not removed.
=> Create and preserve "/var/log/delphix-upgrade" directory

.travis.yml, Makefile, README.md, debian/control.in, debian/postinst, debian/prerm, debian/rules, usr/bin/download-latest-image
Create an instance of the delphix-platform package for each platform
that we support. The package depends on the appropriate version of
delphix-kernel, and contains other platform-specific dependencies where
appropriate.
=> Create platform-specific packages

debian/postinst, var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
This is required for the migration project.
A follow-up change would be to chgrp all the files in `/mds` to `postgres`. We just need to determine when is the right time post-migration to do that.
- http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/391/
- Perform migration. In Linux: stop postgres service (failed), import domain0, start postgres service (success)
- Check that domain0 files created in Illumos are actually owned by `delphix` in Linux.
=> LX-1628 Assign specific UIDs and GIDs for Delphix users

debian/rules
Certain tools that developers commonly use (`lspci` and `ethtool` in
particular) used to be pulled in when we installed `open-vm-tools`. Now we
only install `open-vm-tools` on ESX, so we should add explicit
dependencies on those tools so that they are installed on all platforms.
=> Re-add some tools formerly pulled in by open-vm-tools

debian/rules
We will replace the `bpfcc-tools` that comes with Ubuntu by `bcc-tools` that comes from building the `bcc` linux-pkg project. To avoid flag days, and since we do not have any code dependencies on bpfcc-tools, we start by removing `bpfcc-tool`. `bcc-tools` will be re-added in a subsequent commit.
Note that removing `bpfcc-tools` is necessary for https://github.com/delphix/linux-pkg/pull/12, since `bpfcc-tools` pulls in `libbpfcc`, which conflicts with `libbcc`.
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/419/
=> remove bpfcc-tools

var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
We need to be careful with our delphix-platform service's Ansible code,
and ensure we don't execute commands that would need the ZFS modules
during appliance-build. We accomplish this by causing these tasks not to
run when it detects Ansible is being run in a "chroot" environment.
Unfortunately, a prior change did not properly guard against a "zpool"
invocation, which is causing builds to fail; this change adds the guard,
which should fix the build failures.
=> Don't run zpool command during appliance-build

var/lib/delphix-platform/ansible/apply
The 'apply_playbook' function runs in a sub-shell because it is called
in a pipeline, so the 'exit 1' in that function only exits from the
sub-shell. We need to check the exit status of the sub-shell from the
main shell in order to propagate errors.
Fixes https://github.com/delphix/appliance-build/issues/215
=> Propagate Ansible errors in 'apply' script

etc/delphix-platform/ansible/README, var/lib/delphix-platform/ansible/apply
Previously, in commit 37809a574e9e209a4a58020b7155a13aea85d13d we moved
the location of the delphix-platform service's ansible files from "/etc"
to "/var/lib". Since, at that time, consumers of the delphix-platform
service would still install files in "/etc", we couldn't completely drop
support for the "/etc/delphix-platform/ansible" directory.
Now that consumers have been updated to stop installing files into the
"/etc/delphix-platform/ansible" directory, we can safely drop support
for this directory, and support only the "/var/lib" directory.
=> End support of "/etc/delphix-platform/ansible" directory

etc/cloud/cloud.cfg.d/91-delphix-platform.cfg
Currently our setting for datasource_list is being overridden by a
configuration file generated by the cloud-init package. This results in
cloud-init executing whatever userdata it is passed, even on the
external-standard variant. We can make sure our setting gets used by
renaming the configuration file so that it is read after the one
generated by cloud-init.
=> Fix cloud-init configuration priority

Makefile, debian/postinst, debian/prerm, lib/systemd/system/delphix-migration.service, lib/systemd/system/delphix-platform.service, var/lib/delphix-platform/os-migration
This adds a new service to the appliance: `delphix-migration`.
When the service runs it looks for the `/os-migration` flag file; if the file is not there, then it exits and does nothing.
The `/os-migration` file will be created during a migration upgrade.
- adding migrate_config.py script: http://reviews.delphix.com/r/47101/
- dx_execute call to migrate_config.py and creation of `/os-migration` file (to be posted soon)
- git-ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/600/ (pass)
- Manually tested migration with changes in http://reviews.delphix.com/r/47101/ and upcoming changes to dx_execute. All the services come up except delphix-mgmt (due to LX-1776).
- Ran `systemd-analyze plot` with the service enabled and …
=> LX-1627 Create a service to run post-boot migration logic

var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
Currently running a linux migration upgrade with an internal-dev image consumes 22.9 GB of space on /var/dlpx-upgrade, causing the delphix-platform service to fail on boot as it tries to reduce the quota below the space used.
Relevant error:
```
fatal: [localhost]: FAILED! => {
"changed": false,
"invocation": {
"module_args": {
"createparent": null,
"extra_zfs_properties": {
"compression": "gzip",
"mountpoint": "/var/
"quota": "15g"
},
"name": "rpool/update",
"origin": null,
"state": "present"
}
},
"msg": "cannot set property for 'rpool/update': size is less than current used or reserved space\n
}
```
git-ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/617
=> Bump /var/dlpx-update quota to 30g

var/lib/delphix-platform/os-migration
Description is in the code'd comments.
* Ran migration and made sure delphix-platform service didn't fail because `/var/crash` wasn't empty.
* ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/634/
=> migration: rpool/crashdump must be mounted early on

debian/rules, var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/handlers/main.yaml, var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
This adds the Linux Guest Environment so GCP variant of the delphix platform and configures the override file to ensure that only the appropriate functionality is enabled. We disable the account daemon to prevent users from being added and disable the metadata scripts to prevent running random scripts on the delphix engine.
=> LX-1595 customize gcp guest environment

debian/rules
Remove the delphix-extra package as it will no longer be generated after TOOL-7303 lands.
This package only contains build metadata so the product has no dependency on it.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/723/
=> TOOL-7390 Remove delphix-extra package

lib/systemd/system/delphix-migration.service, var/lib/delphix-platform/os-migration
LX-1806 migration: delphix-migration service should depend on var-delphix.mount
LX-1813 migration: /var/delphix/server should be owned by root
Summary: 
- [LX-1806](https://jira.delphix.com/browse/LX-1806): delphix-migration accesses files on `/var/delphix`, which is mounted asynchronously (it is present in /etc/fstab). Adding a dependency on the `var-delphix.mount` unit waits for /var/delphix to be mounted before starting the service.
- [LX-1813](https://jira.delphix.com/browse/LX-1813): the log rotator in delphix-platform.service failed because some logs (nginx) weren't owned by root. In general on Linux files in `/var/delphix/server` should be owned by root, so we do a recursive chown. While we are there we do the same for mds, to avoid relying on the logic in svc-postgres.sh which …
=> Fixes for LX-1806 and LX-1813

etc/systemd/system/console-setup.service.d/override.conf
Ran `ab-pre-push` successfully except it failed to create the `dcenter` group because of `DLPX-63590`. I verified this boots up fine on `gcp`
=> DLPX-63609 console-setup.service fails to start

var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
update JAVA_HOME to adoptopenJDK
**Testing:**
Linux-pkg run using forked branch of `delphix-platform` - http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/userland/job/pre-push/15/
appliance-build-orchestrator-pre-push : http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/792/ (still running)
Other related changes for appliance-build-orchestrator run - 
app-gate -
changes : https://gitlab.delphix.com/sravya.meda/dlpx-app-gate/commit/d382bb892ff50a936a44d824941099b0143ed037
build : http://selfservice.jenkins.delphix.com/job/dlpx-app-gate/job/master/job/build-package/job/pre-push/442/
masking -
changes : https://gitlab.delphix.com/sravya.meda/dms-core-gate/commit/eddc19da356052cecd5a14ea …
=> update JAVA_HOME to adoptopenjdk

var/lib/delphix-platform/os-migration
This change depends on an app-gate change: http://reviews.delphix.com/r/49164
**Unrelated change**
make sure that both stdout and stderr from migrate_config.py go into the migration log.
- Ran upgrade_minimal. Checked that it passes and made sure that re-indexing was triggered in postgres service logs: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/blackbox-chained/132/
- Ran full upgrade. Checked that the failure in the bug report wasn't reproduced anymore.  http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/blackbox-chained/131/
=> LX-1863 migration: postgres index must be rebuilt after upgrade: delphix-platform change

etc/udev/rules.d/999-delphix-systemd.rules
By default, systemd creates multiple .device units for each block device on
the system: one for the device file in /dev/, one for sysfs representation of
the device, and one for each of the udev-created symlinks to the device. If
the device is partitioned, each of these units is also created for each of the
partitions. For us, creating a zvol typically triggers the creation of 12
.device units. On larger engines, we can easily hit systemd's hard limit of
128K units on a system, at which point systemd stops functioning.
We can work around this by preventing udev from notifying systemd about the
existence of zvols, so that systemd doesn't generate .device units for them.
We don't use these auto-generated units anyway.
=> Prevent systemd from creating .device units for zvols

debian/rules
The "gdb-python" package has been modified to install its files into
"/opt/gdb-python" instead of "/" to prevent conflicts with the "gdb"
packages supplied by Ubuntu. Thus, we can now have both the Ubuntu "gdb"
package, and our custom "gdb-python" package, installed simultaneously.
=> Add "gdb" package dependency

etc/cloud/cloud.cfg.d/91-delphix-platform.cfg
This leverages the changes introduced in https://github.com/delphix/cloud-init/pull/4.
Instead of disabling cloud-init all-together by default (by setting datasource_list to None), we selective disable user-data and public ssh keys passing.
cloud-init: https://github.com/delphix/cloud-init/pull/4
appliance-build: https://github.com/delphix/appliance-build/pull/290
- linux-pkg: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/userland/job/pre-push/50/
- ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1075/
- test that ssh keys are disabled on external-standard but not internal-dev. Also check logs output:
```
internal-dev:
$ grep allow_public_ssh_keys …
```
=> DLPX-64194 Discard public ssh keys and user-data on external product variants

var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
I've opened up a [PR](https://github.com/delphix/appliance-build/pull/293) for appliance-build repo too.
=> crashdump dataset not mounted when generating crash dumps

var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
The "/var/log/delphix-upgrade" directory is no longer used during
upgrade, so we don't need it to be created via delphix-platform anymore.
=> Directory "/var/log/delphix-upgrade" isn't used anymore

var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
The "/var/delphix/dropbox" directory isn't used by upgrade anymore, so
there's no need to have delphix-platform create and manage it.
=> Directory "/var/delphix/dropbox" isn't used anymore

debian/rules
=> DLPX-64434 Linux upgrade, error while unpacking upgrade image, unpack-image: image is corrupt

files/common/etc/default/grub.d/override.cfg
Since the platform runs only trusted code, then we rely on the hypervisor
to mitigate any vulnerabilities. Cloud vendors have made the following
statements:
Azure:
> Microsoft has deployed mitigations across all our cloud services. The
> infrastructure that runs Azure and isolates customer workloads from each
> other is protected. This means that a potential attacker using the same
> infrastructure can’t attack your application using these vulnerabilities.
>     
> This Azure infrastructure update addresses the disclosed vulnerability at
> the hypervisor level and does not require an update to your Windows or
> Linux VM images. However, as always, you should continue to apply security
> best practices for your VM images.
AWS:
> AWS has designed and implemented its infrastructure with …
=> disable spectre/meltdown/mds mitigations

files/common/var/lib/delphix-platform/os-migration
When available, we should use the `by-id` links for device names when importing `domain0` after migration. This has to do with persistent `vdev` names allow for device reordering, etc. See DLPX-64115 for further motivation. This is part of a corresponding change in the `app-gate` which creates `domain0` and modifies the `vdevs` in `domain0` using these names. 
AWS does not provide a `by-dev` link, but I've confirmed that `esx`, `azure`, and `gcp` all do.  
Manually tested this on a platform that does have `by-id` links (ESX) and one that does not (AWS). Confirmed that migration works, `domain0` is correctly imported and the `vdevs` and be removed and readded as expected.
=> Migration: use the by-id links when importing domain0 (except for aws)

files/common/var/lib/delphix-platform/os-migration
The masking home directory has moved between 5.3 and 6.0 and this adds the necessary migration logic for that change. Also, since the id of the `staff` group has changed, it `chowns` the directory so that it is owned by `masking`/`staff`, as was on Illumos.
=> Migrate masking data directory

debian/postinst, debian/prerm, files/common/lib/systemd/system/delphix-migration.service, files/common/lib/systemd/system/delphix-platform.service, files/common/lib/systemd/system/delphix.target
This change adds a new systemd target that will be used to group all of
our Delphix Appliance related services, to make it easy to restart all
services with a single command: "systemctl restart delphix.target"
=> Add "delphix.target" to group all Delphix services

files/common/etc/cloud/cloud.cfg.d/91-delphix-platform.cfg, files/common/usr/bin/unpack-image
This is a rework of http://reviews.delphix.com/r/49972, now that https://jira.delphix.com/browse/TOOL-7917 is fixed.
I have shellcheck 5.0.0 on my laptop and when I run `make check` it complains about:
```
In files/common/usr/bin/unpack-image line 133:
"s/^\(MINIMUM_REBOOT_OPTIONAL_VERSION\)=.*$/\1=$VERSION/" \
^-- SC1117: Backslash is literal in "\(". Prefer explicit escaping: "\\(".
^-- SC1117: Backslash is literal in "\)". Prefer explicit escaping: "\\)".
^-- SC1117: Backslash is literal in "\1". Prefer explicit escaping: "\\1".
```
Ubuntu has shellcheck 4.6.0 which doesn't catch this.
- ab-pre-push --test-upgrade-from trunk: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1509/ (Note that upgrade failed due to …
=> DLPX-64428 prevent cloud-init from modifying ssh keys after first boot

files/common/usr/bin/unpack-image
This review updates unpack-image to hand over unpack duties to a new prepare script (being added in PR https://github.com/delphix/appliance-build/pull/325) to complete the unpack. This design is necessary for SUV phase 2 since the structure of the upgrade image will change with the introduction of a new artifact - the verification package - outside of payload.tar.gz. This change in architecture at a future release (potentially 6.0.2.0) requires Lumen to have logic that can upgrade to versions with and without the updated architecture.
This hand-off design also gives us flexibility in introducing changes to the upgrade image as needed without having to roll-out such changes over multiple releases with prior releases having the necessary logic to handle the changes.
`Manual Tests:`
Manual …
=> DLPX-63558 update unpack-image script in Lumen to accept future wrapper upgrade image and hand-off to complete-unpack script

debian/rules, files/common/var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
Enable CRA on external appliances during the ansible configuration on first boot, leveraging the recently-added `variant` variable.
Also, this change moves the dependency that gets the CRA PAM module installed from `delphix-virtualization` to `delphix-platform` (http://reviews.delphix.com/r/50896/diff removes it from `delphix-virtualization`).
ab pre-push run: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1652/flowGraphTable/
=> CP-2777 CRA enabled for Linux

files/common/var/lib/delphix-platform/os-migration
[DLPX-65118](https://jira.delphix.com/browse/DLPX-65118)
Added section to `os-migration` script to fix dataset permissions after a migration from illumos.  For each `domain0` dataset with a default mountpoint, the parents need other-execute for NFSv4 exports.
**Testing**
1. [ab-pre-push --test-upgrade-from 5.3.5.0](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1712/)
2. Manually tested the script that fixes the permissions on a migrated engine
3. Ran the `shellcheck` and `shfmtcheck` checks against the os-migration script
=> Fix dataset mountpoint permissions post migration for NFSv4 exports

files/common/etc/systemd/system/nfs-config.service.d/override.conf, files/common/usr/lib/systemd/scripts/nfs-version-init.sh
[DLPX-64900](https://jira.delphix.com/browse/DLPX-64900)
This is a work-around for a bug in `rpc.nfsd(8)` where it ignores the `--no-nfs-version 4.1` parameter after a reboot.  We must prime the kernel NFS `version` so that the input string to disable 4.1 and 4.2 succeeds.
**Testing**
1. [ab-pre-push](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1730/)
2. Confirmed that the generated `dlpx-master` VM had the two new files and that reboots persists the expected nfs version (-2 +3 +4 -4.1 -4.2)
3. Manually ran builds of `shellcheck` and `shfmtcheck` checks against the new script
=> rpc.nfsd ignores no-nfs-version parameter at reboot

files/common/var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
`zpool create` can fail on Xen because a udev rule for cdroms is triggered for the disks in the new pool, causing the device to be busy when `zpool` attempts to open it. We work around this by preventing `udev`'s cdrom rules from matching devices named `xvd*` (xen virtual device). We shouldn't need cdroms on AWS.
=> DLPX-61797 zpool create fails sporadically on AWS

files/common/var/lib/delphix-platform/os-migration
On Azure, we want to use the azure-specific links to avoid issues where the by-id links change when the disk is expanded. Because there could be multiple `scsi` directories, we have to build a string that contains a `-d $dir` for each one when running the import command. This change is mutually dependent on the app-gate fix for DLPX-61215
Testing:
Migrated an engine from Illumos to Linux, verified that all disks (include rpool's disk) appear correctly configured. Verified that device removal/addition functioned after migration.
=> Use Azure-specific paths when importing domain0

files/common/lib/systemd/system/rtslib-fb-targetctl.service.d/override.conf, files/common/var/lib/delphix-platform/os-migration
This leverages the functionality added in https://github.com/zfsonlinux/zfs/pull/8975.
ab-pre-push + migration testing: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1836/
=> DLPX-64724 rtslib-fb-targetctl service should wait on domain0 zvol links before starting

.gitignore, files/common/var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
Problem: During upgrade if we decide to rollback, we need to collect the logs and place it in a location that can be accessed from the older location.
Solution: Create a new dataset that will be shared across versions. Place the rollback logs there.
git ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1920/
=> DLPX-65276 Create new dataset that will be shared across versions to store rollback and verify logs

files/common/usr/bin/get-property-from-image
This change adds a new script that can be used to more easily extract
the value of properties contained in an upgrade image's "version.info"
file. In addition to reading the property from the "version.info" file,
this script is responsible for also verifying the signature and checksum
for that file and upgrade image.
This enables consumers to more easily retrieve these properties, without
having to commit to fully unpacking the image.
Here's a few examples:
$ get-property-from-image internal-dev.upgrade.tar.gz VERSION
2019.8.27.4
$ get-property-from-image -s internal-dev.upgrade.tar.gz VERSION
2019.8.27.4
$ get-property-from-image internal-dev.upgrade.tar.gz UNKNOWN
get-property-from-image: failed to get property 'UNKNOWN'
$ get-property-from-image internal-dev.upgrade.tar.gz …
=> Add new script to read version.info properties

files/common/usr/bin/download-latest-image, files/common/usr/bin/get-property-from-image, files/common/usr/bin/unpack-image
The upgrade image file will no longer be compressed, so this change
updates the necessary scripts that interact with that file, such that
they will work with this new file format.
=> Upgrade image file is better left uncompressed

files/common/var/lib/delphix-platform/os-migration
This is the delphix-platform part.
See https://github.com/delphix/appliance-build/pull/355 for more details.
Note that the STRESS_MIGRATION_FAIL_AFTER_DOMAIN0_IMPORT 
and STRESS_MIGRATION_FAIL_AFTER_ZFS_MOUNT options will have more operations between them after LX-1897 is pushed.
=> LX-1948 migration: add first round of stress test options (delphix-platform part)

files/common/usr/lib/systemd/scripts/nfs-version-init.sh, files/common/var/lib/delphix-platform/os-migration
This makes sure any datasets that were still shared when migrating from Illumos will be unshared. We need this since we'll be switching from NFSv3 to NFSv4 for most datasets and the Illumos sharenfs arguments are not compatible with Linux anyway.
migration run: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2030/
=> LX-1897 migration: make sure sharenfs is not set on any dataset after migration

.travis.yml
We've been seeing timeouts when building the Docker container used with
our TravisCI testing. If a command doesn't produce any output for 10
minutes, TravisCI will fail the build the command is running in. Thus,
if "docker build" takes longer than 10 minutes to build the image, our
builds would fail because we had been using the "-q" option when
building the image.
This change removes the "-q" option so that the "docker build" command
will output text as it builds the image, and this output will keep
TravisCI happy even if it takes more than 10 minutes to build the image.
=> Don't use "-q" when building Docker image

files/common/etc/cron.daily/delphix-upgrade-logs
Changed cron job directory from "/var/log/delphix-upgrade" to "/var/tmp/delphix-upgrade",
testing still tbd
=> DLPX-65674 cron job to clean up 'delphix-upgrade' directory is stale

files/common/var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
**Testing**
ab-pre-push:  http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2128/
Confirmed that the VM generated from the above build has the correct `MAKEDUMP_ARGS` setting in `/etc/default/kdump-tools`
**Message Level**
Also update the message level to get a report summary of the makedumpfile in the console, as in:
```
[   53.755074] kdump-tools[765]: STEP [Checking for memory holes  ] : 0.020981 seconds
[   53.771909] kdump-tools[765]: STEP [Excluding unnecessary pages] : 0.120571 seconds
[   53.781250] kdump-tools[765]: STEP [Copying data               ] : 35.703359 seconds
[   53.797194] kdump-tools[765]: STEP [Copying data               ] : 0.000087 seconds
[   53.823060] kdump-tools[765]: Original pages  : …
```
=> Configure kdump so that makedumpfile excludes ZFS ARC file data pages

files/common/lib/systemd/system/delphix-migration.service
See code comment for details.
Note that we couldn't do this originally because `local-fs.target` used to depend on ZFS mounts as well, but we want to run explicitly before ZFS.
Some of the calls that we do to `systemctl daemon-reload` come from `migrate_config` where we migrate the run-state of services such as masking and NTP.
- migration: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2132
=> delphix-migration should run after local-fs.target

files/common/usr/bin/get-property-from-image, files/common/usr/bin/unpack-image
Instead of tags unpack script will accept different exit codes that will be translated in app-stack.
Corresponding app-gate change: http://reviews.delphix.com/r/52590
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2191/
=> DLPX-65501 uploading same upgrade image twice has "unexpected" error

files/common/usr/bin/migrationctl, files/common/var/lib/delphix-platform/os-migration
We add a new "migration complete" flag file that is set by the mgmt stack
when the migration upgrade is completed. This simplifies the logic in
migrationctl to determine when all migration steps are completed.
migrationctl resume functionality is improved to take into account services
that are auto-restarted on failure. Note that this doesn't apply to the mgmt
stack as auto-restart functionality is now disabled in the mgmt stack for
the duration of migration; this makes stress testing easier and also
improves the debugging experience by avoiding restarting multiple times on
the same failures.
depends on app-gate: http://reviews.delphix.com/r/52562/
related appliance-build: https://github.com/delphix/appliance-build/pull/362
See app-gate review.
=> Various improvements to allow migration stress testing in the mgmt stack

files/common/etc/default/grub.d/override.cfg
On our current kernel version (v4.15) the reservation for the
crash kernel is done within the first 896MB of memory by default
in one contiguous chunk. This is problematic for us because we
currently need 512MB for our crash kernel which not only is pretty
big for such a small window but also the allocation is guaranteed
to fail whenever the running kernel (not the crash kernel) is
randomly placed within that window by KASLR.
This patch splits the reservation for the crash kernel into two
parts with one of them being in high memory (e.g. outside the
required region of the first 896MBs). This provides more
flexibility on how we can size it and making the allocations for
the reservation more likely to succeed.
For more background info on the actual bug refer to DLPX-65761.
For more …
=> Sporadic failures when loading the crash kernel in low memory due to KASLR

files/common/var/lib/delphix-platform/os-migration
zfs inherit sharenfs automatically mounts each dataset which has
sharenfs set. However the parent datasets will not be mounted if
they do not have sharenfs set, which will result in the creation
of mount directories in the wrong file systems and will later
cause zfs mount -a to fail with "directory not empty". As a
work around to that bug, we make sure to call zfs mount -a first.
- migration: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2221/
- manually tested migration with VDBs that failed to quiesce and verified that migration completed properly.
=> DLPX-66005 Unquiesced VDBs cause domain0 to fail to mount due to a bug in zfs inherit sharenfs

debian/rules, files/common/usr/bin/get-appliance-version, files/common/usr/bin/get-property-from-image, files/common/usr/bin/unpack-image, scripts/docker-run.sh, scripts/download-signature-key.sh
These changes install the correct image signing keys (both `registration` and `upgrade` keys) for the correct/current Delphix Release version being built.
The signing keys version to use is parameterized via `DELPHIX_SIGNATURE_VERSION` which is passed as environment variable via jenkins build job -> linux-pkg -> delphix_platform package build.  Corresponding jenkins changes are: [devops-gate ](http://reviews.delphix.com/r/52325/)
=> DLPX-65330 Latest public keys are missing in upgrade and migration images

debian/rules
This package provides a neat terminal UI for monitoring various aspects of a system, but it pulls in about 80MB of dependencies and the information it provides can be obtained through other means.
=> Remove glances package

files/common/lib/systemd/system/ssh.service.d/override.conf
The root-cause of this bug is that the ssh systemd service doesn't have
a dependency on network interface configuration.
By default, when using DHCP, the sshd daemon listens on the unspecified
address (0.0.0.0). When the system is configured with static IP
addresses, however, each address gets included individually as
"ListenAddress" directives in /etc/ssh/sshd_config. This results in sshd
binding to and listening on each address individually. If, at startup,
the addresses listed there are not configured, sshd will fail to bind to
them, and will not listen for connections to those addresses. When that
happens, we can see sshd output errors in the ssh service journal:
```
-- Reboot --
Oct 01 22:39:37 localhost sshd[604]: Server listening on 127.0.0.1 port 22.
Oct 01 22:39:37 localhost …
```
=> DLPX-66267 SSH service stops listening to external sources after reboot

files/common/lib/systemd/system/ssh.service.d/override.conf
The root-cause of this bug is that the ssh systemd service doesn't have
a dependency on network interface configuration.
By default, when using DHCP, the sshd daemon listens on the unspecified
address (0.0.0.0). When the system is configured with static IP
addresses, however, each address gets included individually as
"ListenAddress" directives in /etc/ssh/sshd_config. This results in sshd
binding to and listening on each address individually. If, at startup,
the addresses listed there are not configured, sshd will fail to bind to
them, and will not listen for connections to those addresses. When that
happens, we can see sshd output errors in the ssh service journal:
-- Reboot --
Oct 01 22:39:37 localhost sshd[604]: Server listening on 127.0.0.1 port 22.
Oct 01 22:39:37 localhost …
=> DLPX-66652 [Backport of Issue DLPX-66267 to 6.0.0.0] SSH service stops listening to external sources after reboot

debian/rules
Adds debug symbols for dependencies that are built in-house or are particularly important.
=> Add debugging symbols for important packages

debian/rules
=> [Backport to 6.0] Add debugging symbols for important packages

files/common/etc/default/grub.d/override.cfg
Disk should have `noop` I/O scheduler for optimal performance since ZFS will schedule I/Os.
=> DLPX-66227 Disk I/O scheduler should be `noop` rather than default `cfq`

files/common/var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
**Problem**
On ESX, we use by-link links to create pools and to import them on migrated systems. There are two links per device, each with the same base number but with a different prefix (wwn vs scsi). When creating a pool for the first time, we explicitly use the wwn link, if it's available. 
However, it is not possible to specify this when importing a pool and since device links are created by udev asynchronously, sometimes a migrated pool can end up with a combination of wwn and scsi linked devices.
This causes issues when we try to manage the devices with zpool commands passed through the delphix application. The DE thinks the correct name of the pool is the wwn version (since it's now present), but that doesn’t actually exist in the pool and the operation fails. 
**Possible …
=> DLPX-67251 Device removal fails due to inconsistent device names

files/common/var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
Backport of https://github.com/delphix/delphix-platform/pull/162
` git-ab-pre-push --test-upgrade-from 5.3.6.0 -p esx`: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2509/
=> DLPX-67270 [Backport of Issue DLPX-67251 to 6.0.0.0] Device removal fails due to inconsistent device names

files/common/var/lib/delphix-platform/os-migration
Part 1 of 2: http://reviews.delphix.com/r/54101
See JIRA for description.
Caveat:
For the internal-dev variant we deploy other override.conf files under `/etc/systemd/...`, so the files for the same service under `/run/systemd/...` are ignored by systemd. An alternative would be to edit `/etc/systemd` files instead, but the logic would be more complex and prone to failure, so I've opted for this instead.
Testing this change only:
- migration: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2490/
Testing both parts together: see http://reviews.delphix.com/r/54101
=> DLPX-67394 Increase postgres service timeout during migration (Part 2 of 2)

files/common/var/lib/delphix-platform/os-migration
Backport of https://github.com/delphix/delphix-platform/pull/161
migration: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2535/
=> DLPX-67396 [Backport of Issue DLPX-67394 to 6.0.0.0] Increase postgres service timeout during migration

files/common/etc/modprobe.d/blacklist-floppy.conf
See JIRA for details.
- manually tested fix on affected system
- migration pre-push on esx: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2544/
=> DLPX-67583 migration: floppy driver sometimes causes system to hang on boot on 5.0 kernel

files/common/etc/modprobe.d/blacklist-floppy.conf
Clean cherry-pick
migration on ESX: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2551/
=> DLPX-67597 [Backport of Issue DLPX-67583 to 6.0.0.0] migration: floppy driver sometimes causes system to hang on boot on 5.0 kernel

debian/postinst, files/common/etc/update-motd.d/00-delphix, files/common/var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2577/
Before:
```
guild login: sysadmin
Password:
Welcome to Ubuntu 18.04.3 LTS (GNU/Linux 5.0.0-36-generic x86_64)
* Documentation:  https://help.ubuntu.com
* Management:     https://landscape.canonical.com
* Support:        https://ubuntu.com/advantage
* Overheard at KubeCon: "microk8s.status just blew my mind".
https://microk8s.io/docs/commands#microk8s.status
* Canonical Livepatch is available for installation.
- Reduce system reboots and improve kernel security. Activate at:
https://ubuntu.com/livepatch
The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in …
```
=> Disable Ubuntu motd banner and provide a Delphix-specific one.

debian/rules
This adds debug symbols for several libraries used by systemd and dbus. Parts of these libraries provide core bits of infrastructure used by systemd and dbus, so having debug info is important for being able to debug those programs effectively.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2677/
=> Add more systemd-related debug symbol packages 

files/common/var/lib/delphix-platform/os-migration
Cherry-pick backport of https://github.com/delphix/delphix-platform/pull/174, 
https://jira.delphix.com/browse/DLPX-67993
Now, we will attempt to use `by-id` links when importing after migration only if this is a non AWS platform and there are `by-id` links present. 
git-ab-pre-push --test-upgrade-from 5.3.7.0: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2692/
git-ab-pre-push --test-upgrade-from 5.3.7.0 -p esx: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2693/
=> DLPX-67993 [Backport of Issue DLPX-67782 to 6.0.1.0] migration: Failed to import domain0 on i3.4xlarge in AWS

files/common/var/lib/delphix-platform/os-migration
https://jira.delphix.com/browse/DLPX-67782
Now, we will attempt to use `by-id` links when importing after migration only if this is a non AWS platform and there are `by-id` links present. 
I tested this on AWS instances both with and without NVMes (`t2` and `i3`) and on ESX and confirmed that import after migration works fine. 
git-ab-pre-push --test-upgrade-from 5.3.7.0: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2601/
git-ab-pre-push --test-upgrade-from 5.3.7.0 -p esx:
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2689/
=> DLPX-67782 migration: Failed to import domain0 on i3.4xlarge in AWS

debian/postinst, files/common/lib/systemd/system/delphix-migration.service
Issue Number: DLPX-68014
The current behaviour is that the rtslib-fb-targetctl service restarts during a deferred upgrade, causing iSCSI-based VDBs to be inaccessible for a certain time. 
The new behaviour is that rtslib-fb-targetctl is not restarted on upgrade anymore.
This is achieved with 2 changes:
1. We do not re-enable the delphix-migration service when we upgrade the delphix-platform package.
2. We remove delphix-migration as a part of delphix.target.
Either one of those changes should be theoretically sufficient to prevent this bug, but we are doing them both since that is the correct behaviour for this service.
- manually upgraded delphix-platform and restarted …
=> DLPX-68014 iSCSI service interruption during deferred upgrade

files/common/var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
Issue Number: DLPX-68055
On Linux (but not illumos), entering the "shark" password at the CRA response prompt lets the user in.
- When CRA is enabled, disable the `unix` PAM module which does password-based authentication.
App gate review is http://reviews.delphix.com/r/55215/
appliance build pre-push from delphix-platform and linking to that app gate change is running: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2712/flowGraphTable/
Will verify that the generated external image does not have the bug anymore, and will verify that the internal image continues to work as usual.
=> DLPX-68065 [Backport of DLPX-68055 to 6.0.0.0] Can Login with delphix user password instead of using CRA Token

debian/rules
- [ X] Build was run locally and any changes were pushed
- [ X] Lint has passed locally and any fixes were made for failures
- [ X] Bugfix
Issue Number: DLPX-67909
This introduces two new networking diagnostic tools -- traceroute and mtr.
- [ X] No
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2729/
Traceroute output:
```
% traceroute google.com
traceroute to google.com (216.58.194.174), 30 hops max, 60 byte packets
1  _gateway (10.43.0.1)  8.931 ms  8.936 ms  8.920 ms
2  172.16.123.12 (172.16.123.12)  0.200 ms  0.197 ms  0.189 ms
3  6-1-19.ear1.sanjose1.level3.net (4.15.123.65)  0.806 ms  1.191 ms …
```
=> DLPX-67909 Traceroute command/package is missing

files/common/lib/systemd/system/ssh.service.d/override.conf
- [X ] Build was run locally and any changes were pushed
- [X ] Bugfix
Issue Number: DLXP-67961
This changes the bootup logic for ssh to wait until the IP address is stable.
- [ X] No
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2741/
manually applied the change on a system where qa could reproduce the problem to verify that the problem no longer occurs.
=> DLPX-67961 Ssh connection refused after rebooting the engine with static address type

files/common/usr/bin/download-latest-image
This change extends the "download-latest-image" script to add the "-b"
option which allows the user to specify which branch to use when
downloading the upgrade image.
=> Add "-b" to allowing downloading non-master image

files/common/etc/default/grub.d/override.cfg
The 5.3 linux kernel adds a new feature which allows pages to be zeroed when allocating or freeing them: init_on_alloc and init_on_free. init_on_alloc is enabled by default on Ubuntu. ZFS allocates and frees pages frequently (via the ABD structure), e.g. for every disk access. The additional overhead of zeroing these pages is significant. I measured a ~40% regression in performance of an uncached "zfs send ... >/dev/null".
init_on_alloc enabled: http://pharos.delphix.com/shares/export/home/mahrens/FlameGraph/29956.svg
init_on_alloc disabled: http://pharos.delphix.com/shares/export/home/mahrens/FlameGraph/14672.svg
We should disable this in the product by setting init_on_alloc=0 in the GRUB kernel boot parameters.
Linux kernel commit: …
=> DLPX-68392 performance regression on linux kernel 5.3 due to init_on_alloc

files/common/var/lib/delphix-platform/clear-sharenfs, files/common/var/lib/delphix-platform/os-migration
Instead of calling "zfs inherit" recursively on domain0, which tries to
clear sharenfs on every single dataset under domain0, the new approach is
to first identify which datasets have sharenfs set and then clear them one
by one. Datasets that are not mounted are ignored since clearing sharenfs
on unmounted datasets can end-up mounting them without first mounting
their parents, which will automatically create directories for their
mountpoints and later prevent the parent datasets from being mounted
due to their mount directories being not empty.
Note that I'm not opening a PR on master because we are not allowing migrations to 6.1 (Also my testing on master was failing because …
=> DLPX-68141 [Backport of Issue DLPX-68025 to 6.0.1.0] migration: clearing sharenfs on domain0 datasets takes a long time

files/common/usr/bin/migrationctl
This change is meant to prevent confusing support when they use the migrationctl tool.
- migration: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2856/
- tested manually on a system that was rebooted after a successful migration
=> DLPX-67522 [Backport of Issue DLPX-67497 to 6.0.1.0] migrationctl output misleading following a reboot after a successful migration

files/common/var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
Issue Number: DLPX-68188
The login program used for console support logins times out after 60 seconds, which is often insufficient for support when using CRA to obtain the challenge code and enter the response code. On illumos, this timeout was 300 seconds.
Increased the timeout to 300 seconds, on par with illumos,
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2876/flowGraphTable/
Verified that the modified setting indeed results in a timeout at 300 seconds on the console, up from the 60 seconds before the fix.
=> DLPX-68188 Login timeout too aggressive for CRA workflows

debian/rules
Add debug symbols for `bpftrace` and its dependency, `libbcc`
=> Add bpftrace debug symbols

files/common/var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
Clean cherry-pick of https://github.com/delphix/delphix-platform/pull/202 (DLPX-68188) for 6.0/stage.
Issue Number: DLPX-68463
The login program used for console support logins times out after 60 seconds, which is often insufficient for support when using CRA to obtain the challenge code and enter the response code. On illumos, this timeout was 300 seconds.
Increased the timeout to 300 seconds, on par with illumos,
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2888/
Verified that the modified setting indeed results in a timeout at 300 seconds on the console, up from the 60 seconds before the fix.
=> DLPX-68463 [Backport of DLPX-68188 to 6.0.1.0] Login timeout too aggressive for CRA workflows

files/common/var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
ab-pre-push: (unrelated failure in dx-test,linux-tests)
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3111/
Testing on a VM from that pre-push:
```
MAKEDUMP_ARGS="-c -d 31 --message-level 22 --private-page-filter 0x2F5ABDF11ECAC4E"
#KDUMP_KEXEC_ARGS=""
#KDUMP_CMDLINE=""
KDUMP_CMDLINE_APPEND="reset_devices systemd.unit=kdump-tools-dump.service nr_cpus=1 irqpoll nousb ata_piix.prefer_ms_hyperv=0 panic=10"```
```
Again on VMware while looking at the console on a VM that I expected it would run out of memory while loading the crash kernel:
```
[    2.485118]  __page_cache_alloc+0x6a/0xa0
[    2.485118]  pagecache_get_page+0x9c/0x2b0
:set nonu …
=> Crash Kernel should reboot after 10 seconds once it panics

.github/workflows/main.yml, debian/rules, files/common/etc/update-motd.d/00-delphix, files/common/lib/systemd/system/getty@tty1.service.d/override.conf, files/common/lib/systemd/system/serial-getty@ttyS0.service.d/override.conf, files/common/usr/bin/delphix-startup-screen, files/common/usr/bin/get-appliance-version, files/common/usr/bin/get-property-from-image, files/common/usr/bin/unpack-image
This PR add the `delphix-startup-screen` as a python3 program and converts the keyboard logic to use `localectl`. The delphix console is started on both `ttyS0` and `tty1` and it runs as a pre-exec script in the `serial-getty@` and `getty@` services. We override only the `getty@tty1.service` (I think linux can have up to 6 ttys).
=> DLPX-66808 Boot/splash screen for Linux

debian/rules, files/common/etc/udev/rules.d/999-aws-ebs-nvme.rules, files/common/usr/bin/ebs-nvme-mapping
Currently, Delphix Engines on AWS Nitro instances use `/dev/nvmeN` type links for creating pools. This causes problems if we ever need to change between Nitro and non-Nitro instance types - i.e. `domain0` doesn't import.  
Issue Number: https://jira.delphix.com/browse/DLPX-68810
Out strategy is to use the `nvme-cli` package to translate between the nvme-type name to the underlying EBS identifier (`/dev/xvdN`). A new udev rule will invoke this script and create the new links. Then, all AWS DEs will use those links and we don't need to handle the special case in the app-stack. 
This PR introduces the new package, the script and the new udev rule. Other PRs will be needed to …
=> Add scripts and package for use in creating Nitro dev links (master)

debian/rules, files/common/etc/udev/rules.d/999-aws-ebs-nvme.rules, files/common/usr/bin/ebs-nvme-mapping
This is a backport of https://github.com/delphix/delphix-platform/pull/214 to support AWS instances to change to and from Nitro. 
Note that since there is not Nitro support for Illumos DEs, Nitro instances will not be under going migration. I am planning on testing that a migrated engine on 6.0.2.0 can be safely changed to Nitro. 
ab-pre-push (passed):  http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3199/
Manually tested device operations as well as changing instance type for migrated engine.
=> Add nvme-cli, udev rule and script to create nitro ebs dev links (6.0.2.0 backport)

files/common/var/lib/delphix-platform/os-migration
This portion of the fix consumes an overridden ashift value and sets the pool-wide ashift property so that any devices added in the future will use the overridden ashift value.
The pre-upgrade portion of this change can be found here: http://reviews.delphix.com/r/57404
=> DLPX-69340[Backport of DLPX-69339 to 6.0.2.0] migration should handle overridden physical block sizes

files/common/usr/bin/unpack-image
[DLPX-69192](https://jira.delphix.com/browse/DLPX-69192)
[ab-pre-push](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3288/)
Currently the UI handles converting uploaded images from `.tar` to `.upgrade.tar`
```
UI behavior:
the UI uses UpgradeUploadExecutorImpl.java which changes the file name
/**
Returns a randomly generated filename for the given file while preserving its extension.
Assumes (asserts) that the input filename ends in .tar or .tar.gz.
@param inputFilename
@return A randomly generated filename for an upgrade image.
*/
@VisibleForTesting
public static String generateFilename(String inputFilename, boolean random)
Unknown macro: { boolean endsWithTarGz = inputFilename.endsWith(".tar.gz"); checkState(endsWithTarGz || …
```
=> DLPX-69192 Current upgrade image tarfile names are not supported by unpack-image

files/common/usr/bin/unpack-image
[JIRA](https://jira.delphix.com/browse/DLPX-69500)
[ab-pre-push](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3300/)
PR from master: #218
=> DLPX-69500 [Backport of DLPX-69192 to 6.0.3.0] Current upgrade image tarfile names are not supported by unpack-image

files/common/lib/systemd/system/google-instance-setup.service.d/override.conf
google-instance-setup.service hangs within a systemd-nspawn container. This service is unnecessary for the upgrade container. Solution is to add an override parameter that adds a "!container" condition to the service execution.
SUBMITTED git ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3526/
=> DLPX-69870 Upgrade verification fails on GCP because google-instance-setup.service hangs inside container

files/common/lib/systemd/system/google-instance-setup.service.d/override.conf
google-instance-setup.service hangs within a systemd-nspawn container. This service is unnecessary for the upgrade container. Solution is to add an override parameter that adds a "!container" condition to the service execution.
git ab-pre-pusht: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3530/
=> DLPX-69937 [Backport of DLPX-69870 to 6.0.3.0] Upgrade verification fails on GCP because google-instance-setup.service hangs inside container

files/common/etc/sysctl.d/30-nfsv3-ports.conf
This is the first part of the fix for **DLPX-67970**.
We switched to using a fixed port number for `lockd` in DLPX-67666 so lockd uses port 54045 which falls within the dynamic range of 32768-60999 on Linux. Both `statd` and `mountd` ports are allocated from this dynamic range and both are initialized before `lockd`.  This make it possible for one of the four dynamic ports allocated to statd/mountd to use the 54045 value.  When that happens, the `nfs-server` service will fail to start up.
To avoid the possibility for a collision, we reserve ports 54043-54045 for NFSv3 services.
**Testing**
ab-pre-push:  http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3516/
Manually confirmed that the image VM has reserved the ports:
``` …
```
=> DLPX-67970 nfs-service failed to restart after force reboot of engine

files/common/lib/systemd/system/delphix-platform.service, files/common/var/lib/delphix-platform/dynamic-debug
This change enables the following debug statements:
```
/home/ubuntu/6030/aws/linux/drivers/target/target_core_tmr.c:390 [target_core_mod]core_tmr_lun_reset =p "LUN_RESET: %s for [%s] Complete\012"
/home/ubuntu/6030/aws/linux/drivers/target/target_core_tmr.c:383 [target_core_mod]core_tmr_lun_reset =p "LUN_RESET: SCSI-2 Released reservati
/home/ubuntu/6030/aws/linux/drivers/target/target_core_tmr.c:367 [target_core_mod]core_tmr_lun_reset =p "LUN_RESET: %s starting for [%s], tas
/home/ubuntu/6030/aws/linux/drivers/target/target_core_tmr.c:362 [target_core_mod]core_tmr_lun_reset =p "LUN_RESET: TMR caller fabric: %s ini
/home/ubuntu/6030/aws/linux/drivers/target/target_core_tmr.c:322 [target_core_mod]core_tmr_drain_state_list =p "LUN_RESET: ITT[0x%08llx] - %s …
```
=> DLPX-70303 Enable some debug statements in the iSCSI driver

files/common/lib/udev/rules.d/60-dlpx-schedulers.rules
Disable Linux IO scheduler write throttle logic for all disks.
- Manually verified on a system that the tunable was applied and that write throttle was effectively disabled (wb_normal = 0):
```
$ for lat in /sys/block/sd*/queue/wbt_lat_usec; do echo "$lat: $(cat $lat)"; done
/sys/block/sda/queue/wbt_lat_usec: 0
/sys/block/sdb/queue/wbt_lat_usec: 0
/sys/block/sdc/queue/wbt_lat_usec: 0
/sys/block/sdd/queue/wbt_lat_usec: 0
$ sudo bash -c 'for norm in /sys/kernel/debug/block/sd*/rqos/wbt/wb_normal; do echo "$norm: $(cat $norm)"; done'
/sys/kernel/debug/block/sda/rqos/wbt/wb_normal: 0
/sys/kernel/debug/block/sdb/rqos/wbt/wb_normal: 0
/sys/kernel/debug/block/sdc/rqos/wbt/wb_normal: 0
/sys/kernel/debug/block/sdd/rqos/wbt/wb_normal: 0
```
- ab-pre-push (esx): …
=> DLPX-70614 [Backport of DLPX-70512 to 6.0.3.0] Long zio delays likely caused by Linux IO scheduler write throttling logic

files/common/etc/default/grub.d/override.cfg
Clean cherry-pick of commit from master
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3735/flowGraphTable/ (blacbox failures are unrelated)
perf tests - look good
=> DLPX-69049 [Backport of DLPX-68392 to 6.0.3.0] performance regression on linux kernel 5.3 due to init_on_alloc

debian/rules
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3754/flowGraphTable/
I cloned an image on dlpxdc.co based on this build and made sure that ldapsearch was installed via ldap-utils.
=> DLPX-70755 Lumen missing ldapsearch

debian/rules
Backport of #237 
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3769/flowGraphTable/
The upgrade blackbox failure was caused by a QA bug related to Tallaria. QA re-ran that job with Tallaria turned off here: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/blackbox-chained/5154/
=> DLPX-70890 [Backport of DLPX-70755 to 6.0.4.0] Lumen missing ldapsearch

files/common/etc/default/grub.d/override.cfg
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3794/
I manually tested the grub configuration by making the changes to `/etc/default/grub.d/override.cfg`, mounting `rpool/grub`, and updating the grub configuration there using `grub-mkconfig -o /mnt/boot/grub/grub.cfg`. I rebooted and verified that the setting was correct:
```
Y
```
And that USB drivers can no longer be loaded:
```
root@guild:~# modprobe usb-storage
modprobe: ERROR: could not insert 'usb_storage': No such device
```
I also performed an upgrade from 6.0.3.0 to 6.1.0.0 and verified that the kernel command-line upon reboot to the new version correctly included `usbcore.nousb=1`.
=> DLPX-70835 disable usb-storage device module loading in delphix 6.x

files/common/var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/handlers/main.yaml
Skip running google_instance_setup script within a container since it causes delphix-platform to hang within a container with status like :
```
root@sanbhara-trunk-gcp-2:~# systemctl status delphix-platform
● delphix-platform.service - Delphix Appliance Platform Service
Loaded: loaded (/lib/systemd/system/delphix-platform.service; enabled; vendor preset: enabled)
Active: activating (start) since Fri 2020-07-31 19:17:11 UTC; 3h 27min ago
Main PID: 28102 (apply)
CGroup: /system.slice/delphix-platform.service
├─28102 /bin/bash /var/lib/delphix-platform/ansible/apply
├─28115 /usr/bin/python2 /usr/bin/ansible-playbook -vvv -c local -i localhost, -e root_filesystem=rpool/ROOT/delphix.UYhA4Rm/root -e platform=gcp -e variant=internal-qa /var/lib/delphix-platform/ansible/10-delphix-platform/playboo …
```
=> DLPX-70690 GCP upgrade stuck in verifying state with force-not-in-place option

files/common/var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/handlers/main.yaml
Clean cherry-pick of https://github.com/delphix/delphix-platform/pull/242
Testing : 
git ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3827/
git ab-pre-push -p "AWS GCP" -a: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3828/
tested upgrade image from latter run to perform a not-in-place upgrade to 6.0.4.0 version VM. Verification and Upgrade went through fine, and /etc/default/instance_configs.cfg file has the updated configuration from /etc/default/instance_configs.cfg.template.
=> DLPX-71293 [Backport of DLPX-70690 to 6.0.4.0] GCP upgrade stuck in verifying state with force-not-in-place option

files/common/etc/default/grub.d/override.cfg
This is a clean cherry-pick of #240 
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3812/
A similar change will have to be made to appliance-build to cover migrations from 5.3.
=> DLPX-70914 [Backport of DLPX-70835 to 6.0.4.0] disable usb-storage device module loading in delphix 6.x

files/common/lib/udev/rules.d/60-dlpx-schedulers.rules
This is a clean cherry-pick of https://github.com/delphix/delphix-platform/pull/232
- ab-pre-push (esx): http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3698/
- ab-pre-push (aws): http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3699/
=> DLPX-70512 Long zio delays likely caused by Linux IO scheduler write throttling logic

files/common/usr/bin/download-latest-image
This change optimizes the UX of "download-latest-image" script, such
that the user does not necessarily have to specify the image variant to
be downloaded.
This is useful for the case where the script is run on an existing
Delphix appliance, and the user wants the script to download the image
variant that matches the appliance it's being run on.
In this case, the script can (and now does, with this change) detect the
variant of the appliance, and download the corresponding image, without
forcing the user to specify which variant to download.
=> Automatically determine image variant if not specified

debian/rules
See JIRA for more info.
This is half of the work, the other half is here: https://github.com/delphix/delphix-kernel/pull/16
- ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4233/
- ab-pre-push, including changes from https://github.com/delphix/delphix-kernel/pull/16: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4250/
also verified that for `uname -r == 5.4.0-1026-azure`, only `linux-cloud-tools-5.4.0-1026-azure` is installed, and neither `linux-cloud-tools-5.4.0-1031-azure` nor `linux-cloud-tools-azure` is installed any longer.
=> DLPX-72409 Management stack fails on first boot on Azure

debian/rules
This is part of the iSCSI Initiator Project - refer to CP-4220 for more details.
ab-pre-push link: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4457/
Cloning a VM from the above link I manually checked the following:
```
delphix@ip-10-110-232-96:~$ iscsiadm --help
iscsiadm -m discoverydb [ -hV ] [ -d debug_level ] [-P printlevel] [ -t type -p ip:port -I ifaceN ... [ -Dl ] ] | [ [ -p ip:port -t type] [ -o operation ] [ -n name ] [ -v value ] [ -lD ] ]
iscsiadm -m discovery [ -hV ] [ -d debug_level ] [-P printlevel] [ -t type -p ip:port -I ifaceN ... [ -l ] ] | [ [ -p ip:port ] [ -l | -D ] ]
iscsiadm -m node [ -hV ] [ -d debug_level ] [ -P printlevel ] [ -L all,manual,automatic ] [ -U all,manual,automatic ] [ -S ] …
```
=> DLPX-73111 Add open-iscsi package to appliance-build

debian/rules
This is a simple change to add the "update-notifier-common" package as a
dependency. This package is required for the "/var/lib/reboot-required"
file to be properly generated during a upgrade of the appliance.
=> DLPX-73666 file "/var/run/reboot-required" is not properly generated on DEFERRED upgrades

debian/rules
This is a simple change to add the "update-notifier-common" package as a
dependency. This package is required for the "/var/lib/reboot-required"
file to be properly generated during a upgrade of the appliance.
=> Add "update-notifier-common" package

files/common/etc/systemd/system/open-iscsi.service.d/override.conf, files/common/lib/open-iscsi/zpool_on_iscsi.sh
This makes the `open-iscsi` service service **stop** operation zfs aware.  Here we want to make sure ZFS is still not actively using an iSCSI device.  When restarting (or stopping) the `open-iscsi` service, the iscsi devices are torn completely down.  Then during start these devices are rebuilt; they typically have a different device node (`sdN`).  Note that an `open-iscsi` **stop** operation already checks for mounted file systems that are backed by iscsi devices but those checks are not ZFS aware.
We introduce a new check script, `zpool_on_iscsi.sh`, which is similar to the existing `umountiscsi.sh` script.  This new script will return a non-zero result (1) if there is a zfs pool using iSCSI devices which in turn will prevent the `open-iscsi` service from stopping.  The service will log …
=> DLPX-73192 Establish appropriate systemd service dependencies for iSCSI initiator

debian/rules
This backports #145, #179, #203
- ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4831/
- chained upgrade 6.0.6.0 -> 6.0/stage -> master: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/blackbox-chained/7143
=> Backport a few package changes to 6.0/stage

.github/workflows/main.yml, files/common/lib/systemd/system/getty@tty1.service.d/override.conf, files/common/lib/systemd/system/serial-getty@ttyS0.service.d/override.conf, files/common/usr/bin/delphix-startup-screen
DLPX-71998 Chatty systemd events for getty, serial-getty services take up a large percentage of syslog
DLPX-72681 delphix-startup-screen fails with static IP address
DLPX-73286 systemd is restarting locale service every 30 seconds
DLPX-73423 delphix-startup-screen crashes if there's no default route
This changes the getty services to launch the startups screen directly and it's the startup screen that invokes login. This prevents the need for the getty service to restart itself frequently and now the localed and getty restarts only happen when the login session is completed. If nobody logs in via the console then we don't need to restart the service. A further enhancement would be to not display the keyboard layout on the main screen. This would prevent localed from starting unless you …
=> Fix several issues with delphix console screen

files/common/var/lib/delphix-platform/dynamic-debug
I've added a new `pr_debug` statement in the iSCSI target driver in https://github.com/delphix/linux-kernel-generic/pull/5.
This PR enables this debug statement by default.
To be more precise, when an aborted iSCSI command has a DataOut timeout we will see the following message in kern.log:
```
DataOut timeout on interrupted cmd with ITT[0xcb6fef00]
```
- ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4876
- Manual testing from https://github.com/delphix/linux-kernel-generic/pull/5.
=> DLPX-74725 Enable debug for code added for DLPX-72065

files/common/lib/systemd/system/getty@tty1.service.d/override.conf, files/common/lib/systemd/system/serial-getty@ttyS0.service.d/override.conf, files/common/usr/bin/delphix-startup-screen
DLPX-74118 [Backport of DLPX-73286 to 6.0.8.0] systemd is restarting locale service every 30 seconds
DLPX-74511 [Backport of DLPX-71998 to 6.0.8.0] Chatty systemd events for getty, serial-getty services take up a large percentage of syslog
DLPX-74512 [Backport of DLPX-72681 to 6.0.8.0] delphix-startup-screen fails with static IP address
DLPX-74513 [Backport of DLPX-73423 to 6.0.8.0] delphix-startup-screen crashes if there's no default route
=> Backport multiple console fixes

files/common/usr/lib/sysctl.d/30-dlpx-reserved-ports.conf
Issue Number: CP-4790
We are currently reserving 3 ports for nfsv3, and we would like to add another reserved port for the virtualization sdk libs server.
Added a reserved port for the libs server in delphix-platform (54046)
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4902/
=> CP-4790 Reserve a port for the libs server in delphix-platform

files/common/var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/handlers/main.yaml, files/common/var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
Issue Number: DLPX-74859
-
-
-
=> DLPX-74859 Stack fails to come up for GCP engines because delphix-platform service failed

files/common/var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/handlers/main.yaml, files/common/var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
Clean cherry-pick 
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5027/
=> DLPX-74872 [Backport of DLPX-74859 to 6.0.8.0] Stack fails to come up for GCP engines because delphix-platform service failed

files/oci/etc/cloud/cloud.cfg.d/99-delphix-datasource.cfg, files/oci/var/lib/cloud/seed/nocloud/meta-data
Currently, it is not possible to add ssh keys to our internal variants on OCI. This is because we have been using NoCloud as the cloud-init datasource.
This PR changes the behavior for the internal variants by allowing OCI to use the OpenStack datasource.
=> TOOL-10945 Add SSH keys to OCI instances using cloud init

debian/rules
The motivation for this change is two-fold:
- We don't really need this package anymore - we have sdb and crash-python
- We currently have our own downstream branch of crash-util and it is a maintenance burden
This is the first out of 3 changes that will take place throughout
our Delphix repos on github. In this change we just remove the
dependency of the product on crash-util so it stops being installed
on our VMs.
Future work includes stop building the package in linux pkg and
finally deleting our downstream repo. [The deletion of the repo
will have to be delayed though as we may still want to build some
older releases occasionally if the need arises for a support case.]
ab-pre-push:
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-pu …
=> DLPX-75265 Remove crash-util from the product

debian/rules
https://github.com/delphix/delphix-platform/pull/282
Automation: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5085/
Manual Testing: TBA once the above ab-pre-push finishes
=> DLPX-75332 [Backport of DLPX-75265 to 6.0.9.0] Remove crash-util from the product

files/oci/etc/cloud/cloud.cfg.d/99-delphix-datasource.cfg, files/oci/var/lib/cloud/seed/nocloud/meta-data
Clean cherry-pick
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5269/
=> DLPX-74871 [Backport of DLPX-74808 to 6.0.9.0] Add SSH keys to OCI instances using cloud init

files/common/usr/lib/sysctl.d/30-nfsv3-ports.conf
Problem
The docker runtime project no longer needs to reserve a port for the Virtualization SDK Libs Server.
Solution
We are reverting this commit because we switched the communication mechanism for gRPC over to Unix Domain Sockets, and reserving ports are no longer a required change.
=> CP-5096 Revert delphix-platform change

debian/postinst, files/common/lib/open-iscsi/unique-name-check.sh, files/common/lib/systemd/system/iscsi-name-init.service, files/common/usr/bin/get-system-uuid
On Ubuntu, the Initiator IQN is generated when the `open-iscsi` package is installed.  However, we want a unique IQN name to be generated on first boot.  We also want the name generation to not be dependent on performing any iSCSI initiator setup (e.g. the unique IQN should be ready before discovery phase).
Added a new service, `iscsi-name-init.service`, that runs at boot time to generate a unique IQN. This service runs a new script, `unique-name-check`, that will generate a unique initiator IQN.
This new service is based on the Fedora,[ First-time Service Setup](https://docs.fedoraproject.org/en-US/packaging-guidelines/Initial_Service_Setup/) model.
ab-pre-push:
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5270/
pre_checkin: …
=> DLPX-73229 iSCSI initiator name should be unique on each engine

debian/postinst, files/common/lib/open-iscsi/unique-name-check.sh, files/common/lib/systemd/system/iscsi-name-init.service, files/common/usr/bin/get-system-uuid
Clean cherry pick from DLPX-73229 (#300) from commit ec65abf8458ac8fa75daca69b8d1ad489227f82f
Tested with ab-pre-push 
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5386/
=> [Backport of DLPX-73229 to 6.0.9.0] iSCSI initiator name should be unique on each engine

debian/rules
This installs the package created in https://github.com/delphix/appliance-build/pull/493 on the appliance.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5582/
=> DLPX-76340 Install new delphix-build-info package on Delphix Appliance

debian/rules
Clean cherry-pick of #306 
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5726/
=> DLPX-76570 [Backport of DLPX-76340 to 6.0.10.0] Install new delphix-build-info package on Delphix Appliance

debian/rules
Remove python-sh and python3-sh packages.
They were previously used by the migrationctl utility, but are not used anymore. We need to remove the python2 version of the package, python-sh, since it is no longer available on Ubuntu 20.04. I've decided to remove python3-sh as well with the goal of removing unused packages from our appliance.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5747/
=> DLPX-76623 Remove python-sh package

files/common/lib/systemd/system/nfs-server.service.d/override.conf
NFS connections are currently limited to a maximum of 1,340 connections.  This arbitrary limit is calculated based on the maximum number of NFSD threads (currently 64).  Note that on illumos, the maximum number of connections was unlimited by default. With the use of dNFS, we can bump up against this limit which subsequently can have a negative impact on NFS performance.
Ideally we should not have to rely on increasing the number of NFSD threads in order to allow for more connections. So instead, we can set the connection limit to be independent of the NFS thread limit by using the NFSD tunable max_connections.
ab-pre-push:   http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5772/
Checked the image from the ab pre push to confirm …
=> DLPX-76203 Remove the NFS connection limit

files/common/lib/systemd/system/delphix-platform.service
This fix needs to be pushed along with the appgate review to this change which changes when the docker service gets started for the very first time to only after the delphix-platform package has been started and therefore the correct config has been written to the engine.
=> DLPX-76534 Docker0 NIC gets created after upgrade from 6.0/release to 6.0/stage or 6.0/stage to trunk

debian/rules
Cherry-pick of #310 
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5807/
=> DLPX-76772 [Backport of DLPX-76623 to 6.0.10.0] Remove python-sh package

debian/rules
Change #300 introduced `iscsi-name-init.service` and the `get-system-uuid` command.  Since the `get-system-uuid` command requires `dmidecode(8)` it should be a required package for `delphix-platform`.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5836/
Also, from a VM (cloned from the group created above) I verified that dmidecode was present and a dependency of `delphix-platform`.
```
delphix@ip-10-110-215-130:~$ apt-cache depends delphix-platform-aws | grep dmidecode
Depends: dmidecode
```
=> DLPX-76840 delpix-platform is missing dmidecode which iscsi-name-init requires

debian/rules
`delphix-platform` is missing `dmidecode` which `iscsi-name-init` service requires
Clean cherry pick of #319
ab-pre-push:
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5856/
=> DLPX-76870 [Backport of DLPX-76840 for 6.0.10.0]

debian/rules
This reverts #321 as it causes DLPX-76954.
I think the issue is that now that we install ntp from delphix-platform instead of delphix-virtualization we also need to port the logic in preinst/postinst scripts that masks & disables ntp by default.
=> Revert "DLPX-76874 delphix-platform: add dependency on ntp (#321)"

debian/postinst, debian/preinst, debian/rules
This is a follow-up to #321 which was reverted in #322 because it caused DLPX-76954.
The problem with #321 was that previously ntp was installed by delphix-virtualization which took care of masking and disabling the service before it could run, but now that the installation of ntp was done before delphix-virtualiation's preinst/postinst scripts could run, the ntp service was never disabled.
This fix copies the logic from delphix-virtualization to deal with ntp.
One caveat with this new logic is that now on the `internal-dcenter` variant we would no longer run neither systemd-timesyncd nor ntp. Not sure how much of an issue that is though.
An alternative would be to not integrate this and to instead handle DLPX-76872 differently, however I think that having appliance-build first install …
=> DLPX-76874 delphix-platform: add dependency on ntp (re-integrate)

debian/postinst, debian/prerm, files/common/lib/systemd/system/delphix-rpool-upgrade.service
`git-ab-pre-push` is [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6149/)
I specifically chose not to put the `zpool upgrade` call in the existing `delphix-platform` service, to keep it from running inside of the upgrade verification container (and modifying the pool's format from within the container). As a result, the new pool format won't take affect until the first boot, since this means it also will not run at build-time, when building the initial VM disk images. I think that should be fine, and perhaps preferable, since the initial VM disk images are generated on an Ubuntu system, rather than a Delphix system, so the pool features available might be different.
One thing to note when upgrading the pool's on-disk …
=> DLPX-77515 rpool should use lz4 compression

files/common/etc/default/grub.d/override.cfg
See the jira description for full details.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6192/flowGraphTable/
Manual testing:
```
root@ip-10-110-206-157:~# cat /proc/cmdline
BOOT_IMAGE=/ROOT/delphix.Rx4wf3d/root@/boot/vmlinuz-5.4.0-1056-dx2021091105-bbbb0e22c-aws root=ZFS=rpool/ROOT/delphix.Rx4wf3d/root ro console=tty0 console=ttyS0,38400n8 mitigations=off ipv6.disable=1 elevator=noop crashkernel=256M,high crashkernel=256M,low init_on_alloc=0 usbcore.nousb=1 nvme_core.io_timeout=4294967295
root@ip-10-110-206-157:~# cat /sys/module/nvme_core/parameters/io_timeout
4294967295
```
=> DLPX-77577 nvme_core.io_timeout too small and causing problems in EC2

files/common/var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
The `nfs-blkmap.service` is disabled by default but since it is wanted by `nfs-client.target` it is being started on the engine.  We don't use `pNFS` in the product so we now mask `nfs-blkmap.service` to keep it from being started.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6279/
Manual Testing:
inspected an engine from the ab-pre-push image to confirm the service has been masked and is not running anymore:
```
delphix@ip-10-110-227-127:~$ sudo systemctl is-enabled nfs-blkmap.service
masked
delphix@ip-10-110-227-127:~$ sudo systemctl status nfs-blkmap.service
● nfs-blkmap.service
Loaded: masked (/dev/null; bad)
Active: inactive (dead)
delphix@ip-10-110-227-127:~$ sudo journalctl -u nfs-blkmap.service
-- Logs …
```
=> DLPX-75754 nfs-blkmap.service is running when it should be disabled

files/common/var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
The `nfs-blkmap.service` is disabled by default but since it is wanted by `nfs-client.target` it is being started on the engine.  We don't use `pNFS` in the product so we now mask `nfs-blkmap.service` to keep it from being started.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6283/
=> DLPX-75755 [Backport of DLPX-75754 to 6.0.11.0] nfs-blkmap.service is running when it should be disabled

bootstrap/roles/delphix-platform.bootstrap/tasks/main.yml
This will allow us to keep building delphix-platform with the latest version of ansible provided by Ubuntu. See JIRA for more details.
- ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6516/
- manually tested that this works by upgrading ansible on bootstrap image and then building delphix-platform on it.
=> TOOL-12429 delphix-platform fails to build using latest ansible version

debian/rules
This essentially backports #323 and then also #333 which undoes a bunch of the complexity introduced in #323.
This will be pushed at the same time as the remaining work for DLPX-78304
See https://github.com/delphix/appliance-build/pull/627
=> DLPX-78306 [Backport of DLPX-76874 to 6.0.12.0] delphix-platform: add dependency on ntp

files/common/usr/bin/download-latest-image
As part of http://reviews.delphix.com/r/75405/ we are removing devops-gate/master from the
job hierarchy on Jenkins. Need to update all the references.
Remove the references.
Pending
This needs to be merged after the new Jenkins controllers have been deployed. Otherwise, jobs would fail to fetch the right artifacts on S3 since the JOB_NAME will differ.
=> TOOL-12474 Remove Jenkins job references to devops-gate/master in delphix-platform

files/common/usr/bin/download-latest-image
Clean cherrypick of: https://www.github.com/delphix/delphix-platform/pull/340
=> TOOL-12545 [Backport of TOOL-12474 to 6.0/stage] Remove Jenkins job references to devops-gate/master in delphix-platform

files/common/usr/bin/download-release-image
This adds another script to ease the burden of downloading upgrade
images. We already have the "download-latest-image" script that can be
used to download not yet released upgrade images, and this change
compliments that script by adding a "download-released-image" script
that can be used to download already released upgrade images.
=> Add new "download-release-image" script

files/common/lib/systemd/system/google-guest-agent.service.d/override.conf
While reproducing this issue I see the following:
```
Dec  8 18:38:38 ps-78307-2 upgrade-scripts:upgrade-container[26167]: /var/dlpx-update/6.1.0.0-snapshot.20211208124616754+jenkins-ops-appliance-build-master-post-push-23/upgrade-container:do_upgrade_container_in_place:797 die ''\''systemctl restart delphix-platform'\'' failed in '\''delphix.IHYLP0V'\'''
Dec  8 18:38:38 ps-78307-2 upgrade-scripts:upgrade-container[26167]: //var/dlpx-update/6.1.0.0-snapshot.20211208124616754+jenkins-ops-appliance-build-master-post-push-23/common.sh:die:111 basename /var/dlpx-update/6.1.0.0-snapshot.20211208124616754+jenkins-ops-appliance-build-master-post-push-23/upgrade-container
Dec  8 18:38:38 ps-78307-2 upgrade-scripts:upgrade-container[26167]: …
```
=> DLPX-78307 Upgrade tests to trunk failed

files/common/usr/bin/download-release-image
This adds another script to ease the burden of downloading upgrade
images. We already have the "download-latest-image" script that can be
used to download not yet released upgrade images, and this change
compliments that script by adding a "download-released-image" script
that can be used to download already released upgrade images.
=> Add new "download-release-image" script (#341)

debian/rules
Clean cherry-pick of https://github.com/delphix/delphix-platform/pull/347
=> DLPX-78337 [Backport of DLPX-77871 to 6.0.13.0] Need to install the usrmerge package on Ubuntu 20.04

files/common/var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
This pull request attempts to increase the soft limit for "number of open file descriptors" for the users "delphix" and "root" on our engine.
The performance team encountered "out of file descriptors" errors on some of their test cases in the fio test suite. The fio suite itself has a bug which leads to leaked file descriptors during the test runs.
We are increasing the soft limit for "open file descriptors" from the current value of 1024 to 32768. This value was decided during consultations with the performance team. Since we do not see any reason for users other than "delphix" and "root" ever running into this problem, we want to keep the change limited to the affected users only. We are thus going for the minimum set of changes that are needed to fix this problem.
The hard limit is …
=> DLPX-78449 [Backport of DLPX-78424 to 6.0.13.0] Increase ulimit for open files

debian/rules
We don't have any explicit package dependencies on these two packages, yet the product depends on them; this change makes this dependency explicit. This required before landing https://github.com/delphix/appliance-build/pull/665.
=> DLPX-80287 remove unnecessary "recommended" packages from appliance

files/common/lib/systemd/system/zfs-object-agent.service.d/override.conf
This overrides our `zfs-object-agent` systemd service so that it's included as part of `delphix.target`.
=> DLPX-80427 zcache crashes after a deferred upgrade

debian/rules
=> DLPX-80424 [Backport of DLPX-80287 to 6.0.14.0] remove unnecessary "recommended" packages from appliance

files/common/lib/systemd/system/zfs-object-agent.service.d/override.conf
This adds an override.conf file to the zfs-object-agent.service. We add
this to delphix-platform since this is where we do any zfs customizations
which are delphix-specific.
=> DLPX-80598 [Backport of DLPX-80427 to 6.0.14.0] zcache crashes after a deferred upgrade

debian/rules
This PR adds the Azure CLI to our VMs. Thankfully, Ubuntu ships an azure-cli package that Azure doesn't list in their official installation instructions; this reduced the difficulty of adding the utilities to the image. The package is added to the azure dependencies; this means it will not be installed on normal dcenter VMs. This is a slightly drawback of this approach, but it is easy enough to install in that case. It also means the package would not be installed on ESX VMs that customers have on-prem, but using those to talk to azure blob storage doesn't seem like an important use case.
http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/2208/ in progress
=> DOSE-1219 Add Azure CLI to Delphix Engine

files/common/var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/handlers/main.yaml, files/common/var/lib/delphix-platform/ansible/10-delphix-platform/roles/delphix-platform/tasks/main.yml
Multiple customers have reported that their security scanners are
flagging that the SSH server used on the Delphix engine offers
`hmac-sha1` and `umac-64` message authentication codes, which are
considered cryptographically weak.
We are not specifying a MAC configuration in our `sshd_config`,
and the relevant MACs are still included by default as of Ubuntu
20.04.
Modify the delphix-platform ansible script to insert a configuration
which removes all hmac-sha1 and umac-64 MACs from the set of enabled
MACs.
~~NONE -- Preliminary review. The configuration change in question has
been tested manually on an engine but I have not tested using the
ansible change to apply this configuration.~~ See [below](https://github.com/delphix/delphix-platform/pull/379#issuecomment-1159213452
)
=> DLPX-81584 Remove aging and weak sshd message code algorithms

files/common/lib/modprobe.d/10-zfs.conf
Default 32 zvol taskq threads can be a bottleneck in some workloads. We've seen this problem at some customers.
Setting zvol_threads tunable to 256 to improve performance. Taskq threads are created and destroyed dynamically so there should be minimal to no impact on small systems.
A hotfix with the change has been running at customer for a few months without any issue.
Functional - Ran git-ab-pre-push then verified engine cloned from the resulting image have the correct settings.
```
tnguyen@dlpxdc:~$ dc groups list | grep nguyen
dlpx-tnguyen-master                            2022-08-17-17-41  Delphix Engine trunk  2177 1ecb3442
tnguyen@dlpxdc:~$
tnguyen@dlpxdc:~$
tnguyen@dlpxdc:~$ date
Wed Aug 17 22:40:18 UTC 2022
tnguyen@dlpxdc:~$ dc clone-latest dlpx-tnguyen-master tnguyen-master-77850 …
```
=> DLPX-77850 Bump zvol threads count from 32 to 256
